### ISSUE TITLE
`stub` functions from `base` doesn't work when depth >= 2

### ISSUE THREAD

**Issue by krystian8207** [r-lib/mockery#47] opened 2021-04-29 15:46 UTC
Thank you for the great package, it simplifies testing a lot! 

Could you check the below example in which I faced an issue with mocking `base::sample` in nested function.

```
library(mockery)
f <- function() {
  base::sample(LETTERS, 2)
}

g <- function() {
  f()
}

test_that({
  stub(g, 'base::sample', "expected", 3)
  expect_equal(g(), "expected")
})
```

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] testthat_3.0.2 mockery_0.4.2 

loaded via a namespace (and not attached):
 [1] igraph_1.2.6         Rcpp_1.0.6           magrittr_2.0.1       tidyselect_1.1.0     R6_2.5.0             rlang_0.4.10        
 [7] fansi_0.4.2          dplyr_1.0.5          tools_4.0.0          utf8_1.2.1           ellipsis_0.3.1       tibble_3.1.1        
[13] lifecycle_1.0.0      crayon_1.4.1         tidygraph_1.2.0      DataFakeR_0.0.0.9000 purrr_0.3.4          tidyr_1.1.3         
[19] vctrs_0.3.7          glue_1.4.2           compiler_4.0.0       pillar_1.6.0         generics_0.1.0       renv_0.13.2-21      
[25] pkgconfig_2.0.3
```

**Comment by jimhester** [comment] 2021-04-29 16:29
Seems like a duplicate of https://github.com/r-lib/mockery/issues/29 and https://github.com/r-lib/mockery/issues/46?

**Comment by krystian8207** [comment] 2021-04-30 12:02
Yeah, you're right (especially #29) - sorry for opening duplicated issue.

Should we expect having this issue fixed in the nearest future? 
If not, do you know any workarounds for making this work?

Thank you.

**Closed** 2023-10-31 18:15 UTC
